FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install "fastapi[standard]"

COPY src/ ./src/
COPY config/ ./config/

CMD ["fastapi", "run", "src/main.py", "--host", "0.0.0.0", "--port", "8000"]