# update this name to be more informative
# note: whenever you change the file structure, this requires change as well, add this to the README.md
# TODO: add a tool to add sections to the YAML file...

# can be "database", "excel"
ingestion_method: "database"
exportation_method: "excel"

simulate_database: true

file_path:
  input: "data/input/Sample_Salary_Register.xlsx"
  output: "data/output/output_data.xlsx"
  column_schema: "data/other/column_schema.xlsx"

rule_threshold:
  pf: 0.1
  hra: 0.05
  net_payable: 0.01
  z_score: 3.0

rate_data:
  pf: 0.12


